title: Sejeong Moon
logo: "/images/Sejeong_Moon_cropped.jpg?raw=true"
description: 
  <br>
  Pursuing a Master’s degree in <br>
  Data Science at Texas A&M University, <br>
  to become a Data Scientist with a <br>
  robust understanding of business field.
  <br><br>
  <a href="https://www.linkedin.com/in/sejeong-moon/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
